### ISSUE TITLE
The Index of Maximum

### ISSUE THREAD

**Issue by dreamkidd** [vicboma1/Kotlin-Examples-Problems#1]
```
fun indexOfMax(a: IntArray): Int? {
    return a.indices.maxBy { a[it] } ?: null
}
```

dose this works?

**Comment by vicboma1** [comment]
Text 6 & 7 are failed @dreamkidd 
Pardon me to answer you now

![screen shot 2016-12-07 at 16 03 05](https://cloud.githubusercontent.com/assets/3646388/20972894/b1b0257e-bc96-11e6-9329-873a73e8459f.png)
